name: Continuous Integration
on: pull_request

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  docker-linux:
    name: Build Linux and Docker
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.405

      - name: Build
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake
  docker-windows:
    name: Build Windows and Docker
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.405

      - name: Build
        run: |
          dotnet tool restore
          dotnet cake --image-directory="windows.ltsc2019"